### ISSUE TITLE
Images

### ISSUE THREAD

**Issue by ryuta69** [ryuta69/elly.vim#1]
<img alt="elly.vim" src="https://user-images.githubusercontent.com/41639488/98116862-3d084780-1eec-11eb-9d3c-6937554cb285.png">

**Comment by ryuta69** [comment]
<img alt="elly.vim" src="https://user-images.githubusercontent.com/41639488/98123673-814c1580-1ef5-11eb-8520-06af6404e738.png">

**Comment by ulwlu** [comment]
<img alt="elly.vim" src="https://user-images.githubusercontent.com/41639488/100524967-21990f80-3200-11eb-9ecc-46d197f5e221.png">

**Comment by ulwlu** [comment]
<img alt="elly.vim" src="https://user-images.githubusercontent.com/41639488/100525315-14c9eb00-3203-11eb-8cc9-ad0116d800c1.png">

**Comment by ulwlu** [comment]
![elly.vim](https://user-images.githubusercontent.com/41639488/100526196-fc110380-3209-11eb-913a-22adfa3c19ab.png)

**Comment by ulwlu** [comment]
![elly.vim](https://user-images.githubusercontent.com/41639488/100792090-771e2800-345d-11eb-9843-afd5a08e42e6.png)

**Comment by ulwlu** [comment]
<img alt="elly.vim" src="https://user-images.githubusercontent.com/41639488/100796896-ad12da80-3464-11eb-90ec-11bdb92cb488.png">

**Comment by ulwlu** [comment]
<img alt="elly.vim" src="https://user-images.githubusercontent.com/41639488/100799586-a5553500-3468-11eb-99a0-7254a606229f.png">

**Comment by ulwlu** [comment]
<img alt="elly.vim" src="https://user-images.githubusercontent.com/41639488/101771605-8bcd8080-3b2d-11eb-9711-3a34ad8f3bfd.png">

**Comment by ulwlu** [comment]
![ss 1](https://user-images.githubusercontent.com/41639488/124693031-a6c46f80-df19-11eb-9455-8fab1a5f682b.png)

**Comment by ulwlu** [comment]
![elly.vim](https://user-images.githubusercontent.com/41639488/124696330-cced0e00-df1f-11eb-8059-a16a74c24777.png)
