### ISSUE TITLE
Font used in the screenshots

### ISSUE THREAD

**Issue by shin-ra** [ryuta69/elly.vim#3]
What's the font being used in the screenshots? 
The theme is looking great.

**Comment by ryuta69** [comment]
Hi. I used https://github.com/ryanoasis/nerd-fonts 's  Italic font.

If you are using MacOS and iTerm2,

1. `brew cask install font-hack-nerd-font`
2. `iTerm -> Preferences -> Profiles -> Text -> Font`, then select `Hack Nerd Font` and `Italic`

**Comment by shin-ra** [comment]
Thank you, and sorry I just realized one of the screenshots had the font name.
